default_language_version:
  python: python3.6
exclude: ^\.gitignore$
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
      - id: seed-isort-config
        args: [--application-directories, 'src']
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.16
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: double-quote-string-fixer
      - id: flake8
        additional_dependencies: ["flake8-bugbear", "pep8-naming"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.14.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.3.0
    hooks:
      - id: rst-backticks
